config/routes.rb
Dotsearchfile::Application.routes.draw do
  resources :users do
    resources :search_subscriptions
    resources :search_ownerships
    resources :list_subscriptions
    resources :list_ownerships
  end
  resources :searches
  resources :tags
  resources :search_lists
  resources :sessions, :only => [:new, :create, :destroy]
    
  
  resources :tags do
    get :autocomplete_tag, :on => :collection
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "home#index"
end

  

app/controllers/search_ownerships_controller.rb
class SearchOwnershipsController < ApplicationController
  # GET /search_ownerships
  # GET /search_ownerships.json
  def index
    @search_ownerships = SearchOwnership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_ownerships }
    end
  end

  # GET /search_ownerships/1
  # GET /search_ownerships/1.json
  def show
    @search_ownership = SearchOwnership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_ownership }
    end
  end

  # GET /search_ownerships/new
  # GET /search_ownerships/new.json
  def new
    @search_ownership = SearchOwnership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_ownership }
    end
  end

  # GET /search_ownerships/1/edit
  def edit
    @search_ownership = SearchOwnership.find(params[:id])
  end

  # POST /search_ownerships
  # POST /search_ownerships.json
  def create
    @search_ownership = SearchOwnership.new(params[:search_ownership])

    respond_to do |format|
      if @search_ownership.save
        format.html { redirect_to @search_ownership, notice: 'Search ownership was successfully created.' }
        format.json { render json: @search_ownership, status: :created, location: @search_ownership }
      else
        format.html { render action: "new" }
        format.json { render json: @search_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_ownerships/1
  # PUT /search_ownerships/1.json
  def update
    @search_ownership = SearchOwnership.find(params[:id])

    respond_to do |format|
      if @search_ownership.update_attributes(params[:search_ownership])
        format.html { redirect_to @search_ownership, notice: 'Search ownership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_ownerships/1
  # DELETE /search_ownerships/1.json
  def destroy
    @search_ownership = SearchOwnership.find(params[:id])
    @search_ownership.destroy

    respond_to do |format|
      format.html { redirect_to search_ownerships_url }
      format.json { head :no_content }
    end
  end
end

app/views/search_ownerships/_form.html.erb
<%= form_for(@search_ownership) do |f| %>
  <% if @search_ownership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search_ownership.errors.count, "error") %> prohibited this search_ownership from being saved:</h2>

      <ul>
      <% @search_ownership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/search_ownerships/edit.html.erb
<h1>Editing search_ownership</h1>

<%= render 'form' %>

<%= link_to 'Show', @search_ownership %> |
<%= link_to 'Back', search_ownerships_path %>

app/views/search_ownerships/index.html.erb
<h1>Listing search_ownerships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @search_ownerships.each do |search_ownership| %>
  <tr>
    <td><%= link_to 'Show', search_ownership %></td>
    <td><%= link_to 'Edit', edit_search_ownership_path(search_ownership) %></td>
    <td><%= link_to 'Destroy', search_ownership, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Search ownership', new_search_ownership_path %>

app/views/search_ownerships/new.html.erb
<h1>New search_ownership</h1>

<%= render 'form' %>

<%= link_to 'Back', search_ownerships_path %>

app/views/search_ownerships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_search_ownership_path(@search_ownership) %> |
<%= link_to 'Back', search_ownerships_path %>