config/routes.rb
Dotsearchfile::Application.routes.draw do
  resources :users do
    resources :search_subscriptions
    resources :search_ownerships
    resources :list_subscriptions
    resources :list_ownerships
  end
  resources :searches
  resources :tags
  resources :search_lists
  resources :sessions, :only => [:new, :create, :destroy]
    
  
  resources :tags do
    get :autocomplete_tag, :on => :collection
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "home#index"
end

  

app/models/user.rb
class User < ActiveRecord::Base
  has_one :preference, :dependent => :destroy
  
  has_many :filter_ownerships, :dependent => :destroy
  has_many :owned_filters, :through => :filter_ownerships, :source => :filter, :include => :tags, :dependent => :destroy

  has_many :list_ownerships, :dependent => :destroy
  has_many :list_subscriptions, :dependent => :destroy
  has_many :lists, :through => :list_subscriptions, :include => :tags
  has_many :owned_lists, :through => :list_ownerships, :source => :list, :include => :tags, :dependent => :destroy
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }
   
  before_save :encrypt_password
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i             
  validates :email, :presence => true, :format => { :with => email_regex }
  validates_uniqueness_of :email
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  private
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")  
    end
  
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
  
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # Kind of a profile page, that's the approach I'm taking
  def show
    @user = User.find(params[:id])
    @lists = @user.lists
    @owned_filters = @user.owned_filters
    @owned_lists = @user.owned_lists
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      format.html do
        if @user.save
          sign_in @user
          flash[:success] = "Welcome to DotSearchFile"
          redirect_to @user
        else
          @title = "Sign up"
          render :new
        end
      end
      format.json { render json: @user.errors, status: :unprocessable_entity}
    end
  end
end

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages" %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>		
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :password %>
  	<%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>	
  </div>
  <div class="actions">
  	<%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div id="notice"><%= notice %></div>
<div id="name" class="name"><%= @user.name %></div>
<div id="list_subscriptions" class="list_subscriptions">
  List subscriptions
  <ul>
  	<%= link_to 'Edit', user_list_subscriptions_path(@user) %>
  	<% @lists.each do |list| %>
  	  <% @list = list %>
  	  <li><%= render :template => "lists/show" %></li>
  	<% end %>
  </ul>
</div>
<div id="list-ownerships" class="list-ownerships">
  Lists you own
  <ul>
  	<% @owned_lists.each do |list| %>
  	  <% @list = list %>
  	  <li><%= render :template => "lists/show"%>
  	<% end %>
  </ul>
</div>
<div id="search-ownerships">
  Filters you own
  <ul>
  	<%= link_to 'New', new_search_path %>
    <% @owned_filters.each do |filter| %>
      <% @filter = filter %>
      <li><%= render :template => "filters/show" %></li>
    <% end %>
  </ul>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>