config/routes.rb
Dotsearchfile::Application.routes.draw do
  resources :users do
    resources :search_subscriptions
    resources :search_ownerships
    resources :list_subscriptions
    resources :list_ownerships
  end
  resources :searches
  resources :tags
  resources :search_lists
  resources :sessions, :only => [:new, :create, :destroy]
    
  
  resources :tags do
    get :autocomplete_tag, :on => :collection
  end
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => "home#index"
end

  

app/models/list_ownership.rb
class ListOwnership < ActiveRecord::Base
  belongs_to :search_list
  belongs_to :user
end

app/controllers/list_ownerships_controller.rb
class ListOwnershipsController < ApplicationController
  # GET /list_ownerships
  # GET /list_ownerships.json
  def index
    @list_ownerships = ListOwnership.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_ownerships }
    end
  end

  # GET /list_ownerships/1
  # GET /list_ownerships/1.json
  def show
    @list_ownership = ListOwnership.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_ownership }
    end
  end

  # GET /list_ownerships/new
  # GET /list_ownerships/new.json
  def new
    @list_ownership = ListOwnership.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list_ownership }
    end
  end

  # GET /list_ownerships/1/edit
  def edit
    @list_ownership = ListOwnership.find(params[:id])
  end

  # POST /list_ownerships
  # POST /list_ownerships.json
  def create
    @list_ownership = ListOwnership.new(params[:list_ownership])

    respond_to do |format|
      if @list_ownership.save
        format.html { redirect_to @list_ownership, notice: 'List ownership was successfully created.' }
        format.json { render json: @list_ownership, status: :created, location: @list_ownership }
      else
        format.html { render action: "new" }
        format.json { render json: @list_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_ownerships/1
  # PUT /list_ownerships/1.json
  def update
    @list_ownership = ListOwnership.find(params[:id])

    respond_to do |format|
      if @list_ownership.update_attributes(params[:list_ownership])
        format.html { redirect_to @list_ownership, notice: 'List ownership was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_ownership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_ownerships/1
  # DELETE /list_ownerships/1.json
  def destroy
    @list_ownership = ListOwnership.find(params[:id])
    @list_ownership.destroy

    respond_to do |format|
      format.html { redirect_to list_ownerships_url }
      format.json { head :no_content }
    end
  end
end

app/views/list_ownerships/_form.html.erb
<%= form_for(@list_ownership) do |f| %>
  <% if @list_ownership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_ownership.errors.count, "error") %> prohibited this list_ownership from being saved:</h2>

      <ul>
      <% @list_ownership.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/list_ownerships/edit.html.erb
<h1>Editing list_ownership</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_ownership %> |
<%= link_to 'Back', list_ownerships_path %>

app/views/list_ownerships/index.html.erb
<h1>Listing list_ownerships</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_ownerships.each do |list_ownership| %>
  <tr>
    <td><%= link_to 'Show', list_ownership %></td>
    <td><%= link_to 'Edit', edit_list_ownership_path(list_ownership) %></td>
    <td><%= link_to 'Destroy', list_ownership, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List ownership', new_list_ownership_path %>

app/views/list_ownerships/new.html.erb
<h1>New list_ownership</h1>

<%= render 'form' %>

<%= link_to 'Back', list_ownerships_path %>

app/views/list_ownerships/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_list_ownership_path(@list_ownership) %> |
<%= link_to 'Back', list_ownerships_path %>